# Site settings
title: Herman Barrantes # site title
description: >- # site description
  Blog personal de Herman Barrantes sobre desarrollo de software, 
  sistemas operativos, tecnología y cultura geek.
lang: es-CR # default lang
timezone: America/Costa_Rica # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/barrantesgerman/blog # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Herman Barrantes # author name
  bio: >- # tell to the world
    Ingeniero de software y arquitecto, actualmente enfocado en 
    arquitectura de nube, tecnologías sin servidor y microservicios.
  username: barrantesgerman # general username
  github: barrantesgerman # github username
  twitter: barrantesgerman # twitter username
  facebook: hermanbarrantes # facebook username
  email: barrantesgerman@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://www.hermanbarrantes.dev" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
